// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {RewardsDistributor} from "../src/RewardsDistributor.sol";
import {MockERC20} from "./mocks/MockERC20.sol";

/// @notice Compatibility between the off-chain engine and the RewardsDistributor (engine spec §7.3).
///         `fixtures/merkle-epoch.json` is generated by the TypeScript engine
///         (`engine: merkle-fixture`): if the leaf encoding ever diverges, this test
///         breaks, not the first holder who tries to claim.
contract MerkleFixtureTest is Test {
    using stdJson for string;

    MockERC20 token;
    RewardsDistributor dist;
    string json;
    bytes32 root;
    uint256 budget;

    address owner = address(0xA11CE);
    address scorer = address(0x5C0);
    address guardian = address(0x6A);

    function setUp() public {
        json = vm.readFile(string.concat(vm.projectRoot(), "/test/fixtures/merkle-epoch.json"));
        root = json.readBytes32(".root");
        budget = json.readUint(".budget");
        token = new MockERC20();
        dist = new RewardsDistributor(address(token), owner, scorer, guardian, block.timestamp);
        vm.warp(block.timestamp + dist.EPOCH_LENGTH()); // epoch 0 must have ended before its root
        // The per-epoch cap is 20% of the free balance: the distributor holds five times the budget.
        token.mint(address(dist), budget * 5);
        vm.prank(scorer);
        dist.setEpochRoot(0, root, budget);
        vm.warp(block.timestamp + dist.CLAIM_DELAY());
    }

    function _claim(uint256 i) internal view returns (address account, uint256 amount, bytes32[] memory proof) {
        string memory p = string.concat(".claims[", vm.toString(i), "]");
        account = json.readAddress(string.concat(p, ".account"));
        amount = json.readUint(string.concat(p, ".amount"));
        proof = json.readBytes32Array(string.concat(p, ".proof"));
    }

    function test_every_engine_claim_is_redeemable() public {
        uint256 n;
        while (vm.keyExistsJson(json, string.concat(".claims[", vm.toString(n), "]"))) n++;
        assertEq(n, 3, "the fixture has three beneficiaries");
        uint256 paid;
        for (uint256 i = 0; i < n; i++) {
            (address account, uint256 amount, bytes32[] memory proof) = _claim(i);
            vm.prank(account);
            dist.claim(0, amount, proof);
            assertEq(token.balanceOf(account), amount, "claimed amount differs from the leaf amount");
            paid += amount;
        }
        assertEq(paid, budget, "the sum of the rewards is the committed budget");
        assertEq(dist.committed(), 0, "once rewards are claimed nothing stays committed");
    }

    function test_an_engine_proof_does_not_pay_a_different_amount() public {
        (address account, uint256 amount, bytes32[] memory proof) = _claim(0);
        vm.prank(account);
        vm.expectRevert(RewardsDistributor.InvalidProof.selector);
        dist.claim(0, amount + 1, proof);
    }

    function test_an_engine_proof_does_not_pay_someone_else() public {
        (, uint256 amount, bytes32[] memory proof) = _claim(0);
        vm.prank(address(0xBAD));
        vm.expectRevert(RewardsDistributor.InvalidProof.selector);
        dist.claim(0, amount, proof);
    }
}
